<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'Blog' => '',
    'Categories' => '',
    'Category' => '',
    'Celphone' => '',
    'Color' => '',
    'Contact' => '',
    'Contact ID' => '',
    'Contact Images' => '',
    'Contacts' => '',
    'Create' => '',
    'Create Category' => '',
    'Create Contact' => '',
    'Create Image' => '',
    'Create Option' => '',
    'Defaultpage' => '',
    'Delete' => '',
    'Description' => '',
    'E-mail or Username' => '',
    'Facebookpage' => '',
    'Favorite' => '',
    'File' => '',
    'Fullname' => '',
    'Gallery' => '',
    'Googlepluspage' => '',
    'ID' => '',
    'Imagem' => '',
    'Images' => '',
    'Language' => '',
    'Login' => '',
    'Login to access the System' => '',
    'Mail' => '',
    'Name' => '',
    'Options' => '',
    'Password' => '',
    'Phone' => '',
    'Rating' => '',
    'Reset' => '',
    'Search' => '',
    'Select' => '',
    'Send Image' => '',
    'Shortname' => '',
    'Successfully deleted' => '',
    'Successfully included' => '',
    'Successfully updated' => '',
    'Theme' => '',
    'Twitterpage' => '',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'Upload successfully' => '',
    'Website' => '',
];
