<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => 'Tem certeza que deseja excluir esse item?',
    'Avatar' => 'Imagem',
    'Blog' => 'Blog',
    'Categories' => 'Categorias',
    'Category' => 'Categoria',
    'Celphone' => 'Celular',
    'Contacts' => 'Contatos',
    'Create' => 'Novo',
    'Create Category' => 'Nova Categoria',
    'Create Contact' => 'Novo Contato',
    'Delete' => 'Excluir',
    'Description' => 'Descrição',
    'E-mail or Username' => 'E-mail ou Usuário',
    'Facebookpage' => 'Facebook',
    'Favorite' => 'Favorito',
    'Fullname' => 'Nome Completo',
    'Googlepluspage' => 'Google+',
    'ID' => 'ID',
    'Login' => 'Usuário',
    'Login to access the System' => 'Autentique para acessar o sistema',
    'Mail' => 'E-mail',
    'Name' => 'Nome',
    'Password' => 'Senha',
    'Phone' => 'Telefone',
    'Rating' => 'Avaliação',
    'Reset' => 'Redefinir',
    'Search' => 'Pesquisar',
    'Shortname' => 'Apelido',
    'Twitterpage' => 'Twitter',
    'Update' => 'Alterar',
    'Update {modelClass}: ' => 'Alterar',
    'Website' => 'Website',
];
